### ISSUE TITLE
Is there a more efficient way to build this matrix

### ISSUE THREAD

**Issue by KirstieJane** [MELDProject/meld#1]
At the moment we read in individual subjects to concatenate them into one matrix per site.

Each subject has around 35 features at each of 300,000 vertices.

Is there a way to read in this data and write it out into a single all subject matrix that is memory efficient.

https://github.com/MELDProject/meld/blob/083ff38b57b4bd05478b9fa8ddbc5114057e1718/scripts/create_training_data.py#L59

**Comment by jamespjh** [comment]
Maybe try python's HDF5 interface?

**Comment by jamespjh** [comment]
Your existing solution already avoids large copies, as all_subjects_data is a python list not a numpy array, and extend is efficient for lists. (They're amortised constant time appends), and the code correctly converts to a numpy array only at the end. So there's no inefficient copies in the existing code anyway, except from the big final copy on line 61

**Comment by jamespjh** [comment]
But the storage to disk on line 64 would probably be better as a H5Py save: https://www.h5py.org

**Comment by jamespjh** [comment]
Oh, and if you're looping over a python array with an auxiliary counter you want to use `enumerate` rather than explicitly initialising and incrementing k. https://docs.python.org/3.7/library/functions.html#enumerate 
https://docs.python.org/2.3/whatsnew/section-enumerate.html

**Comment by kwagstyl** [comment]
Thank you for the suggestion @jamespjh 
The other thing I was considering was running the for loop with a text file open and writing out each individual "subject_data" as it is created. That would remove the need for all_subjects_data every being stored in memory. It looses the efficiency of H5Py, but means that I would never need to create the big final directory

**Comment by jamespjh** [comment]
http://geology.beer/2015/02/10/hdf-for-large-arrays/

**Comment by jamespjh** [comment]
I'm not sure, but maybe using a chunked resizable h5py file would get the best of both worlds? Load a row, add to the HDF5 file, discard the loaded row, loop. I *think* that would give you what looks logically like a big tensor as far as the file is concerned, but without ever having the whole thing in memory.
