### ISSUE TITLE
WARNING : division using '/' with python2 gives integers if inputs are integers. 

### ISSUE THREAD

**Issue by mathrip** [MELDProject/meld#4]
In python2,  the results of `c=a/b` is an integer if a and b are integers. 
example : 
```
a=3
b=2
c=a/b
------
c=1
```
This could have lead to wrong values of the z_measure in the intrasubject normalisation? 

https://github.com/MELDProject/meld/blob/622fcb490ee7c52949982b806a7901a201830b18/scripts/intrasubject_normalisation.py#L46

**Comment by kwagstyl** [comment]
Good to catch as a potential issue.
I think we were lucky here as np.std() outputs as floats even if calculated over integers so I think it wouldn't ever have given wrong values.

**Comment by mathrip** [comment]
That's a good point! We are ok then, I'll close the issue
